kumuluzee:
  name: dummy-producer
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  server:
    base-url: http://169.51.13.160 # zunanji URL
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://169.51.13.160:31711
    ttl: 20
    ping-interval: 15

rest-config:
  string-property: local_Tuesday
  boolean-property: false
  integer-property: -42

# ETCD kubernetes deployment -> github rso-customers @ jmezna
